job_specifications:
- id: cntkjob
  auto_complete: true
  shm_size: 256m
  tasks:
  - docker_image: alfpark/cntk:2.1-gpu-1bitsgd-py36-cuda8-cudnn6-intelmpi-refdata
    resource_files:
    - blob_source: https://raw.githubusercontent.com/Azure/batch-shipyard/master/recipes/CNTK-GPU-Infiniband-IntelMPI/docker/set_up_cntk.sh
      file_path: set_up_cntk.sh
    multi_instance:
      num_instances: pool_current_dedicated
      pre_execution_command: source set_up_cntk.sh
      mpi:
        runtime: intelmpi
        options:
        - -np $np
        - -ppn $ngpus
        - -hosts $AZ_BATCH_HOST_LIST
    command: /bin/bash -c "python -u /cntk/Examples/Image/Classification/ResNet/Python/TrainResNet_CIFAR10_Distributed.py --network resnet20 -q 1 -a 0 --datadir /cntk/Examples/Image/DataSets/CIFAR-10 --outputdir $AZ_BATCH_TASK_WORKING_DIR/output"
