job_specifications:
- id: cntkjob
  auto_complete: true
  shm_size: 256m
  tasks:
  - docker_image: alfpark/cntk:2.1-gpu-1bitsgd-py36-cuda8-cudnn6-intelmpi-refdata
    multi_instance:
      num_instances: pool_current_dedicated
      pre_execution_command: source /cntk/activate-cntk; source /opt/intel/compilers_and_libraries/linux/mpi/bin64/mpivars.sh
      mpi:
        runtime: intelmpi
        processes_per_node: nvidia-smi -L | wc -l
    command: python -u /cntk/Examples/Image/Classification/ResNet/Python/TrainResNet_CIFAR10_Distributed.py --network resnet20 -q 1 -a 0 --datadir /cntk/Examples/Image/DataSets/CIFAR-10 --outputdir $AZ_BATCH_TASK_WORKING_DIR/output
