{
 "title": "Batch Shipyard Dashboard",
 "description": "Dashboard for Batch Shipyard resources",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Resource",
    "query": "label_values(node_boot_time_seconds, job)"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(node_boot_time_seconds{job=~\"$job\"}, instance)"
   },
   {
    "name": "port",
    "label": "Port (NE)",
    "query": "label_values(node_boot_time_seconds{instance=~\"$node:(.*)\"}, instance)"
   },
   {
    "name": "port_ca",
    "label": "Port (CA)",
    "query": "label_values(cadvisor_version_info{instance=~\"$node:(.*)\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Aggregate Overview for Resource",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Nodes",
   "type": "singlestat",
   "description": "Total number of nodes",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{job=~\"$job\"}) without (cpu, mode))"
    }
   ]
  },
  {
   "title": "Average Uptime",
   "type": "singlestat",
   "description": "System uptime",
   "gridPos": { "h": 2, "w": 4, "x": 2, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(node_time_seconds{job=~\"$job\"}) - avg(node_boot_time_seconds{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "singlestat",
   "description": "Total Memory",
   "gridPos": { "h": 2, "w": 4, "x": 6, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "description": "Aggregate Network traffic on all devices",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{job=~\"$job\"}[1m]))",
     "legendFormat": "receive"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{job=~\"$job\"}[1m]))",
     "legendFormat": "transmit"
    }
   ]
  },
  {
   "title": "Min Free Ephemeral FS Space",
   "type": "singlestat",
   "description": "Smallest free ephemeral disk space on a node",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(node_filesystem_avail_bytes{device=\"/dev/sdb1\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Min Free Root FS Space",
   "type": "singlestat",
   "description": "Smallest free root disk space on a node",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(node_filesystem_avail_bytes{mountpoint=\"/\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "description": "Core usage across all nodes",
   "gridPos": { "h": 4, "w": 4, "x": 2, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (1 - avg(irate(node_cpu_seconds_total{mode=\"idle\",job=~\"$job\"}[1m])))"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "description": "Memory Used by all nodes",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (sum(node_memory_MemTotal_bytes{job=~\"$job\"}) - sum(node_memory_MemAvailable_bytes{job=~\"$job\"})) / sum(node_memory_MemTotal_bytes{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Ephemeral FS Usage",
   "type": "singlestat",
   "description": "Average used ephemeral FS",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * ((sum(node_filesystem_size_bytes{device=\"/dev/sdb1\",job=~\"$job\"}) - sum(node_filesystem_avail_bytes{device=\"/dev/sdb1\",job=~\"$job\"})) / sum(node_filesystem_size_bytes{device=\"/dev/sdb1\",job=~\"$job\"}))"
    }
   ]
  },
  {
   "title": "Root FS Usage",
   "type": "singlestat",
   "description": "Average Used Root FS",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * ((sum(node_filesystem_size_bytes{mountpoint=\"/\",job=~\"$job\"}) - sum(node_filesystem_avail_bytes{mountpoint=\"/\",job=~\"$job\"})) / sum(node_filesystem_size_bytes{mountpoint=\"/\",job=~\"$job\"}))"
    }
   ]
  },
  {
   "title": "Total Cores",
   "type": "singlestat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{job=~\"$job\"}) without (mode))"
    }
   ]
  },
  {
   "title": "Container Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containers Core Usage (1m avg)",
     "type": "graph",
     "description": "Core usage for containers",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",instance=~\"($node):$port_ca\",job=~\"$job\"}[1m])) by (name, image, job, instance)",
       "legendFormat": "{{name}}: {{image}} ({{job}}: {{instance}})"
      }
     ]
    },
    {
     "title": "Container Memory Usage (1m avg)",
     "type": "graph",
     "description": "Container Memory Usage (Working Set Size)",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{image!=\"\",instance=~\"($node):$port_ca\",job=~\"$job\"}) by (name, image, job, instance)",
       "legendFormat": "{{name}}: {{image}} ({{job}}: {{instance}})"
      }
     ]
    },
    {
     "title": "Container Network I/O (1m avg)",
     "type": "graph",
     "description": "Container Network I/O",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{image!=\"\",instance=~\"($node):$port_ca\",job=~\"$job\"}[1m])) by (name, image, job, instance)",
       "legendFormat": "{{name}}: {{image}} ({{job}}: {{instance}})"
      }
     ]
    },
    {
     "title": "Container Disk Usage (1m avg)",
     "type": "graph",
     "description": "Container Disk Usage",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_fs_usage_bytes{image!=\"\",instance=~\"($node):$port_ca\",job=~\"$job\"}) by (name, image, job, instance)",
       "legendFormat": "{{name}}: {{image}} ({{job}}: {{instance}})"
      }
     ]
    },
    {
     "title": "Container Aggregate Write (1m avg)",
     "type": "graph",
     "description": "Container Write Usage",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_fs_writes_bytes_total{image!=\"\",instance=~\"($node):$port_ca\",job=~\"$job\"}) by (name, image, job, instance)",
       "legendFormat": "{{name}}: {{image}} ({{job}}: {{instance}})"
      }
     ]
    },
    {
     "title": "Container Aggregate Read (1m avg)",
     "type": "graph",
     "description": "Container Read Usage",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 58 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_fs_reads_bytes_total{image!=\"\",instance=~\"($node):$port_ca\",job=~\"$job\"}) by (name, image, job, instance)",
       "legendFormat": "{{name}}: {{image}} ({{job}}: {{instance}})"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU/Memory/Network Detailed Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short", "label": "Percentage" }
     ],
     "targets": [
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode=\"system\",instance=~\"($node):$port\",job=~\"$job\"}[5m])) * 100",
       "legendFormat": "System - Processes executing in kernel mode"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='user',instance=~\"($node):$port\",job=~\"$job\"}[5m])) * 100",
       "legendFormat": "User - Normal processes executing in user mode"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='nice',instance=~\"($node):$port\",job=~\"$job\"}[5m])) * 100",
       "legendFormat": "Nice - Niced processes executing in user mode"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"($node):$port\",job=~\"$job\"}[5m])) * 100",
       "legendFormat": "Idle - Waiting for something to happen"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='iowait',instance=~\"($node):$port\",job=~\"$job\"}[5m])) * 100",
       "legendFormat": "Iowait - Waiting for I/O to complete"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='irq',instance=~\"($node):$port\",job=~\"$job\"}[5m])) * 100",
       "legendFormat": "Irq - Servicing interrupts"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='softirq',instance=~\"($node):$port\",job=~\"$job\"}[5m])) * 100",
       "legendFormat": "Softirq - Servicing softirqs"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='steal',instance=~\"($node):$port\",job=~\"$job\"}[5m])) * 100",
       "legendFormat": "Steal - Time spent in other operating systems when running in a virtualized environment"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='guest',instance=~\"($node):$port\",job=~\"$job\"}[5m])) * 100",
       "legendFormat": "Guest - Time spent running a virtual CPU for a guest operating system"
      }
     ]
    },
    {
     "title": "Memory Stack",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"($node):$port\",job=~\"$job\"} - node_memory_MemFree_bytes{instance=~\"($node):$port\",job=~\"$job\"} - node_memory_Buffers_bytes{instance=~\"($node):$port\",job=~\"$job\"} - node_memory_Cached_bytes{instance=~\"($node):$port\",job=~\"$job\"} - node_memory_Slab_bytes{instance=~\"($node):$port\",job=~\"$job\"} - node_memory_PageTables_bytes{instance=~\"($node):$port\",job=~\"$job\"} - node_memory_SwapCached_bytes{instance=~\"($node):$port\",job=~\"$job\"}",
       "legendFormat": "Apps - Memory used by user-space applications"
      },
      {
       "expr": "node_memory_PageTables_bytes{instance=~\"($node):$port\",job=~\"$job\"}",
       "legendFormat": "PageTables - Memory used to map between virtual and physical memory addresses"
      },
      {
       "expr": "node_memory_SwapCached_bytes{instance=~\"($node):$port\",job=~\"$job\"}",
       "legendFormat": "SwapCache - Memory that keeps track of pages that have been fetched from swap but not yet been modified"
      },
      {
       "expr": "node_memory_Slab_bytes{instance=~\"($node):$port\",job=~\"$job\"}",
       "legendFormat": "Slab - Memory used by the kernel to cache data structures for its own use (caches like inode, dentry, etc)"
      },
      {
       "expr": "node_memory_Cached_bytes{instance=~\"($node):$port\",job=~\"$job\"}",
       "legendFormat": "Cache - Parked file data (file content) cache"
      },
      {
       "expr": "node_memory_Buffers_bytes{instance=~\"($node):$port\",job=~\"$job\"}",
       "legendFormat": "Buffers - Block device (e.g. harddisk) cache"
      },
      {
       "expr": "node_memory_MemFree_bytes{instance=~\"($node):$port\",job=~\"$job\"}",
       "legendFormat": "Unused - Free memory unasigned"
      },
      {
       "expr": "(node_memory_SwapTotal_bytes{instance=~\"($node):$port\",job=~\"$job\"} - node_memory_SwapFree_bytes{instance=~\"($node):$port\",job=~\"$job\"})",
       "legendFormat": "Swap - Swap space used"
      },
      {
       "expr": "node_memory_HardwareCorrupted_bytes{instance=~\"($node):$port\",job=~\"$job\"}",
       "legendFormat": "Harware Corrupted - Amount of RAM that the kernel identified as corrupted / not working"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total{instance=~\"($node):$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{device}} - Receive"
      },
      {
       "expr": "irate(node_network_transmit_bytes_total{instance=~\"($node):$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{device}} - Transmit"
      }
     ]
    }
   ]
  },
  {
   "title": "Filesystem Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Filesystem space available",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_avail_bytes{instance=~\"($node):$port\",job=~\"$job\",device!~'rootfs'}",
       "legendFormat": "{{mountpoint}} - Available"
      }
     ]
    },
    {
     "title": "File Nodes Free",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "File Nodes" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_files_free{instance=~\"($node):$port\",job=~\"$job\",device!~'rootfs'}",
       "legendFormat": "{{mountpoint}} - Free file nodes"
      }
     ]
    },
    {
     "title": "File Descriptor",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Files" }
     ],
     "targets": [
      {
       "expr": "node_filefd_maximum{instance=~\"($node):$port\",job=~\"$job\"}",
       "legendFormat": "Max open files"
      },
      {
       "expr": "node_filefd_allocated{instance=~\"($node):$port\",job=~\"$job\"}",
       "legendFormat": "Open files"
      }
     ]
    },
    {
     "title": "File Nodes Size",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "File Nodes" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_files{instance=~\"($node):$port\",job=~\"$job\",device!~'rootfs'}",
       "legendFormat": "{{mountpoint}} - File nodes total"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Space Used",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{instance=~\"($node):$port\",job=~\"$job\",device!~'rootfs'} - node_filesystem_avail_bytes{instance=~\"($node):$port\",job=~\"$job\",device!~'rootfs'}",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "I/O Usage Read / Write",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total{instance=~\"($node):$port\",job=~\"$job\",device=~\"[a-z]*[a-z]\"}[5m])",
       "legendFormat": "{{device}} - Successfully read bytes"
      },
      {
       "expr": "irate(node_disk_written_bytes_total{instance=~\"($node):$port\",job=~\"$job\",device=~\"[a-z]*[a-z]\"}[5m])",
       "legendFormat": "{{device}} - Successfully written bytes"
      }
     ]
    },
    {
     "title": "Disk IOps",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "iops", "label": "IO read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_reads_completed_total{instance=~\"($node):$port\",job=~\"$job\",device=~\"[a-z]*[a-z]\"}[5m])",
       "legendFormat": "{{device}} - Reads completed"
      },
      {
       "expr": "irate(node_disk_writes_completed_total{instance=~\"($node):$port\",job=~\"$job\",device=~\"[a-z]*[a-z]\"}[5m])",
       "legendFormat": "{{device}} - Writes completed"
      }
     ]
    },
    {
     "title": "I/O Usage Times",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "ms", "label": "Milliseconds" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_io_time_seconds_total{instance=~\"($node):$port\",job=~\"$job\",device=~\"[a-z]*[a-z]\"} [5m])",
       "legendFormat": "{{device}} - Milliseconds spent doing I/Os"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Detailed Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Traffic by Packets",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "pps", "label": "Packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_packets_total{instance=~\"($node):$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{device}} - Receive"
      },
      {
       "expr": "irate(node_network_transmit_packets_total{instance=~\"($node):$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{device}} - Transmit"
      }
     ]
    },
    {
     "title": "Network Traffic Errors",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "pps", "label": "Packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_errs_total{instance=~\"($node):$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{device}} - Receive errors"
      },
      {
       "expr": "irate(node_network_transmit_errs_total{instance=~\"($node):$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{device}} - Rransmit errors"
      }
     ]
    },
    {
     "title": "Network Traffic Drop",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "pps", "label": "Packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_drop_total{instance=~\"($node):$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{device}} - Receive drop"
      },
      {
       "expr": "irate(node_network_transmit_drop_total{instance=~\"($node):$port\",job=~\"$job\"}[5m])",
       "legendFormat": "{{device}} - Transmit drop"
      }
     ]
    },
    {
     "title": "NF Contrack",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "short", "label": "Entries" }
     ],
     "targets": [
      {
       "expr": "node_nf_conntrack_entries{instance=~\"($node):$port\",job=~\"$job\"}",
       "legendFormat": "NF conntrack entries"
      },
      {
       "expr": "node_nf_conntrack_entries_limit{instance=~\"($node):$port\",job=~\"$job\"}",
       "legendFormat": "NF conntrack limit"
      }
     ]
    },
    {
     "title": "Sockstat TCP",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short", "label": "Sockets" }
     ],
     "targets": [
      {
       "expr": "node_sockstat_TCP_alloc{instance=~\"($node):$port\",job=~\"$job\"}",
       "legendFormat": "TCP_alloc - Allocated sockets"
      },
      {
       "expr": "node_sockstat_TCP_inuse{instance=~\"($node):$port\",job=~\"$job\"}",
       "legendFormat": "TCP_inuse - Tcp sockets currently in use"
      },
      {
       "expr": "node_sockstat_TCP_mem{instance=~\"($node):$port\",job=~\"$job\"}",
       "legendFormat": "TCP_mem - Used memory for tcp"
      },
      {
       "expr": "node_sockstat_TCP_orphan{instance=~\"($node):$port\",job=~\"$job\"}",
       "legendFormat": "TCP_orphan - Orphan sockets"
      },
      {
       "expr": "node_sockstat_TCP_tw{instance=~\"($node):$port\",job=~\"$job\"}",
       "legendFormat": "TCP_tw - Sockets wating close"
      }
     ]
    },
    {
     "title": "Sockstat UDP",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "short", "label": "Sockets" }
     ],
     "targets": [
      {
       "expr": "node_sockstat_UDPLITE_inuse{instance=~\"($node):$port\",job=~\"$job\"}",
       "legendFormat": "UDPLITE_inuse - Udplite sockets currently in use"
      },
      {
       "expr": "node_sockstat_UDP_inuse{instance=~\"($node):$port\",job=~\"$job\"}",
       "legendFormat": "UDP_inuse - Udp sockets currently in use"
      },
      {
       "expr": "node_sockstat_UDP_mem{instance=~\"($node):$port\",job=~\"$job\"}",
       "legendFormat": "UDP_mem - Used memory for udp"
      }
     ]
    },
    {
     "title": "Sockstat Used",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "short", "label": "Sockets" }
     ],
     "targets": [
      {
       "expr": "node_sockstat_sockets_used{instance=~\"($node):$port\",job=~\"$job\"}",
       "legendFormat": "Sockets_used - Sockets currently in use"
      }
     ]
    },
    {
     "title": "Sockstat Memory Size",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_sockstat_TCP_mem_bytes{instance=~\"($node):$port\",job=~\"$job\"}",
       "legendFormat": "TCP_mem_bytes - "
      },
      {
       "expr": "node_sockstat_UDP_mem_bytes{instance=~\"($node):$port\",job=~\"$job\"}",
       "legendFormat": "UDP_mem_bytes - "
      }
     ]
    }
   ]
  },
  {
   "title": "System Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Load",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short", "label": "Load" }
     ],
     "targets": [
      {
       "expr": "node_load1{instance=~\"($node):$port\",job=~\"$job\"}",
       "legendFormat": "Load 1m"
      },
      {
       "expr": "node_load5{instance=~\"($node):$port\",job=~\"$job\"}",
       "legendFormat": "Load 5m"
      },
      {
       "expr": "node_load15{instance=~\"($node):$port\",job=~\"$job\"}",
       "legendFormat": "Load 15m"
      }
     ]
    },
    {
     "title": "Processes State",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short", "label": "Processes" }
     ],
     "targets": [
      {
       "expr": "node_procs_blocked{instance=~\"($node):$port\",job=~\"$job\"}",
       "legendFormat": "Processes blocked waiting for I/O to complete"
      },
      {
       "expr": "node_procs_running{instance=~\"($node):$port\",job=~\"$job\"}",
       "legendFormat": "Processes in runnable state"
      }
     ]
    },
    {
     "title": "Processes Memory",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "decbytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "process_virtual_memory_bytes{instance=~\"($node):$port\",job=~\"$job\"}",
       "legendFormat": "Processes virtual memory size in bytes"
      },
      {
       "expr": "process_resident_memory_bytes{instance=~\"($node):$port\",job=~\"$job\"}",
       "legendFormat": "Processes resident memory size in bytes"
      }
     ]
    },
    {
     "title": "File Descriptors",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "short", "label": "Descriptors" }
     ],
     "targets": [
      {
       "expr": "process_max_fds{instance=~\"($node):$port\",job=~\"$job\"}",
       "legendFormat": "Maximum open file descriptors"
      },
      {
       "expr": "process_open_fds{instance=~\"($node):$port\",job=~\"$job\"}",
       "legendFormat": "Open file descriptors"
      }
     ]
    },
    {
     "title": "Context Switches / Interrupts",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "irate(node_context_switches_total{instance=~\"($node):$port\",job=~\"$job\"}[5m])",
       "legendFormat": "Context switches"
      },
      {
       "expr": "irate(node_intr_total{instance=~\"($node):$port\",job=~\"$job\"}[5m])",
       "legendFormat": "Interrupts"
      }
     ]
    },
    {
     "title": "Processes  Forks",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "short", "label": "Forks / sec" }
     ],
     "targets": [
      {
       "expr": "rate(node_forks_total{instance=~\"($node):$port\",job=~\"$job\"}[5m])",
       "legendFormat": "Processes forks second"
      }
     ]
    },
    {
     "title": "Time Syncronized Drift",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "s", "label": "Seconds" }
     ],
     "targets": [
      {
       "expr": "node_timex_estimated_error_seconds{instance=~\"($node):$port\",job=~\"$job\"}",
       "legendFormat": "Estimated error in seconds"
      },
      {
       "expr": "node_timex_offset_seconds{instance=~\"($node):$port\",job=~\"$job\"}",
       "legendFormat": "Time offset in between local system and reference clock"
      },
      {
       "expr": "node_timex_maxerror_seconds{instance=~\"($node):$port\",job=~\"$job\"}",
       "legendFormat": "Maximum error in seconds"
      }
     ]
    }
   ]
  },
  {
   "title": "NFS Client Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "NFS Client Connections",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short", "label": "Connections" }
     ],
     "targets": [
      {
       "expr": "node_mountstats_nfs_transport_connect_total{instance=~\"($node):$port\",job=~\"$job\"}",
       "legendFormat": "NFS client connections"
      }
     ]
    },
    {
     "title": "NFS Client I/O",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(node_mountstats_nfs_write_bytes_total{instance=~\"($node):$port\",job=~\"$job\"}[1m]))",
       "legendFormat": "Write"
      },
      {
       "expr": "sum(rate(node_mountstats_nfs_read_bytes_total{instance=~\"($node):$port\",job=~\"$job\"}[1m]))",
       "legendFormat": "Read"
      }
     ]
    }
   ]
  },
  {
   "title": "NFS Kernel Server Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "NFS Kernel Server Connections",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short", "label": "Connections" }
     ],
     "targets": [
      {
       "expr": "node_nfsd_connections_total{instance=~\"($node):$port\",job=~\"$job\"}",
       "legendFormat": "NFS kernel server connections"
      }
     ]
    },
    {
     "title": "NFS Kernel Server I/O",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(node_nfsd_disk_bytes_written_total{instance=~\"($node):$port\",job=~\"$job\"}[1m]))",
       "legendFormat": "Write"
      },
      {
       "expr": "sum(rate(node_nfsd_disk_bytes_read_total{instance=~\"($node):$port\",job=~\"$job\"}[1m]))",
       "legendFormat": "Read"
      }
     ]
    }
   ]
  }
 ]
}