name: $(SourceBranch)$(Rev:.r)

jobs:
  - job: ReplicateSingularityImages
    pool:
      vmImage: ubuntu-20.04
    steps:
      - template: replicate-singularity.yml
        parameters:
          enabled: True
