batch_shipyard:
  storage_account_settings: mystorageaccount
global_resources:
  singularity_images:
    signed:
      - image: library://alfpark/mvapich/mvapich:2.3.2
        signing_key:
          fingerprint: B55AC090E5139130C112A5783C4D545F457737EB
