batch_shipyard:
  storage_account_settings: mystorageaccount
  use_shipyard_docker_image: false
global_resources:
  singularity_images:
    unsigned:
    - library://vincent.labonte/mpi/mpibench:openmpi
