job_specifications:
- id: mpibench-intelmpi
  auto_complete: true
  tasks:
  - docker_image: vincentlabo/mpibench:intelmpi
    command: /mpiBench/mpiBench -e 1K
    multi_instance:
      num_instances: pool_current_dedicated
      pre_execution_command: export MANPATH=/usr/share/man; source /opt/intel/compilers_and_libraries/linux/mpi/bin64/mpivars.sh
      mpi:
        runtime: intelmpi
        processes_per_node: nproc
