credentials:
  batch:
    account_key: <batch account key>
    account_service_url: <batch account service url>
  storage:
    mystorageaccount:
      account: <storage account name>
      account_key: <storage account key>
      endpoint: core.windows.net
