job_specifications:
- id: <job id>
  auto_complete: true
  shared_data_volumes:
  - azureblob_vol
  tasks:
  - docker_image: msmadl/symsgd:0.0.1
    multi_instance:
      num_instances: pool_current_dedicated
    command: /parasail/run_parasail.sh -w /parasail/supersgd -l 1e-4 -k 32 -m 1e-2 -e 10 -r 10 -f $AZ_BATCH_NODE_SHARED_DIR/azblob/<container_name from the data shredding configuration file> -t 1 -g 1 -d $AZ_BATCH_TASK_WORKING_DIR/models -b $AZ_BATCH_NODE_SHARED_DIR/azblob/<container_name from the data shredding configuration file>
