job_specifications:
- id: docker-openfoam-openmpi-ib-job
  auto_complete: true
  auto_scratch:
    setup: dependency
    num_instances: pool_current_dedicated
  tasks:
  - docker_image: vincentlabo/openfoam:openmpi-ib
    additional_docker_run_options:
    - --cap-add=sys_nice
    resource_files:
    - blob_source: https://raw.githubusercontent.com/Azure/batch-shipyard/master/recipes/OpenFOAM-Infiniband-OpenMPI/docker/set_up_sample.sh
      file_path: set_up_sample.sh
    multi_instance:
      num_instances: pool_current_dedicated
      pre_execution_command: source set_up_sample.sh
      mpi:
        runtime: openmpi
        options:
          - -np $np
          - --hostfile $hostfile
          - -x $mpienvopts
    command: simpleFoam -parallel
