job_specifications:
- id: openfoamjob
  auto_complete: true
  auto_scratch: true
  tasks:
  - docker_image: alfpark/openfoam:4.0-gcc-openmpi
    resource_files:
    - blob_source: https://raw.githubusercontent.com/vincentlabonte/batch-shipyard/singularity3/recipes/OpenFOAM-TCP-OpenMPI/docker/set_up_sample.sh
      file_path: set_up_sample.sh
    multi_instance:
      num_instances: pool_current_dedicated
      pre_execution_command: source set_up_sample.sh
      mpi:
        runtime: openmpi
        executable_path: $mpirun
        options:
          - -np $np
          - --hostfile $hostfile
          - -x PATH
          - -x LD_LIBRARY_PATH
          - -x MPI_BUFFER_SIZE
          - -x $mpienvopts
          - -x $mpienvopts2
    command: simpleFoam -parallel
